/**
 * Projects data - Auto-generated by scripts/import-projects.js
 * You can also manually edit this file to customize project entries
 */

export interface Project {
  id: string;
  title: string;
  slug: string;
  description: string;
  longDescription?: string;
  tech: string[];
  github_url: string;
  demo_url?: string;
  image?: string;
  featured: boolean;
  stars?: number;
  category?: string;
}

export const projectsData: Project[] = [
  {
    id: '1',
    title: 'TerraNova',
    slug: 'terranova',
    description:
      'AI-powered city planning application that generates sustainable urban layouts using cutting-edge web technologies.',
    longDescription:
      'Built for the "Co-creating with GPT-5" hackathon on lab. TerraNova uses artificial intelligence to help urban planners design eco-friendly, efficient cities with optimized infrastructure and green spaces.',
    tech: ['JavaScript', 'AI', 'Urban Planning', 'GPT'],
    github_url: 'https://github.com/Harshad2321/TerraNova',
    demo_url: 'https://parth2619.github.io/TerraNova/',
    image: '/terranova.png',
    featured: true,
    category: 'AI',
  },
  {
    id: '2',
    title: 'Exoplanet Classifier',
    slug: 'exoplanet-classifier',
    description:
      'Advanced AI system to hunt for exoplanets using NASA\'s treasure trove of space data (KOI, K2, TESS).',
    longDescription:
      'Solution for NASA Space Apps Challenge 2024: "A World Away: Hunting for Exoplanets with AI". Developed machine learning models to classify and identify potentially habitable exoplanets from NASA datasets.',
    tech: ['Python', 'Machine Learning', 'TensorFlow', 'NASA Data'],
    github_url: 'https://github.com/Harshad2321/Exoplanet-Classifier-NASA-KOI-K2-TESS-',
    demo_url: 'https://huggingface.co/spaces/ParthKoshti/Nasa-Exoplanet-Classifier',
    image: '/Nasa.png',
    featured: true,
    stars: 1,
    category: 'AI',
  },
  {
    id: '3',
    title: 'ByteNotes',
    slug: 'bytenotes',
    description:
      'Full-stack web application that allows users to upload PDF documents and ask AI-powered questions about their content.',
    longDescription:
      'Built with React, Node.js, and Hugging Face integration. ByteNotes makes document analysis easy by letting you chat with your PDFs using natural language.',
    tech: ['TypeScript', 'React', 'Node.js', 'Hugging Face', 'AI'],
    github_url: 'https://github.com/Harshad2321/ByteNotes',
    demo_url: 'https://harshad2321.github.io/ByteNotes/',
    image: '/bytenotes.png',
    featured: true,
    category: 'Full-Stack',
  },
  {
    id: '4',
    title: 'Legal AI Simplifier',
    slug: 'legal-ai-simplifier',
    description:
      'AI-powered platform that transforms complex legal documents into clear, actionable insights using Google Cloud AI.',
    longDescription:
      'Makes legal jargon accessible to everyone. Upload any legal document and get simplified explanations, key points extraction, and actionable recommendations.',
    tech: ['TypeScript', 'Google Cloud AI', 'NLP', 'React'],
    github_url: 'https://github.com/Harshad2321/Legal-AI-Simplifier',
    demo_url: 'https://harshad2321.github.io/Legal-AI-Simplifier/',
    image: '/Legal Ai.png',
    featured: true,
    category: 'AI',
  },
  {
    id: '5',
    title: 'AgriSakha',
    slug: 'agrisakha',
    description:
      'Smart multilingual, AI-powered platform providing personalized, real-time crop advisory with voice-first and offline-first design.',
    longDescription:
      'Built by Crop Bytes team. AgriSakha helps farmers make informed decisions with AI-driven crop recommendations, weather forecasts, and pest management advice.',
    tech: ['JavaScript', 'AI', 'Voice Recognition', 'PWA'],
    github_url: 'https://github.com/Harshad2321/AgriSakha',
    demo_url: 'https://agrisakha.vercel.app/',
    image: '/Agrisakha.png',
    featured: true,
    stars: 1,
    category: 'AI',
  },
  {
    id: '6',
    title: 'Solvra',
    slug: 'solvra',
    description: 'Advanced optimization and algorithmic search tools built in Python.',
    longDescription:
      'Collection of optimization algorithms and search techniques implemented from scratch. Great for learning algorithmic problem-solving.',
    tech: ['Python', 'Algorithms', 'Optimization'],
    github_url: 'https://github.com/Harshad2321/Solvra',
    featured: true,
    stars: 1,
    category: 'Algorithms',
  },
  {
    id: '7',
    title: 'MindMetrics',
    slug: 'mindmetrics',
    description: 'Data analysis and machine learning experiments using Jupyter Notebooks.',
    tech: ['Python', 'Jupyter', 'Data Science', 'ML'],
    github_url: 'https://github.com/Harshad2321/MindMetrics',
    demo_url: 'https://harshad2321.github.io/MindMetrics/',
    image: '/mindmetrics.png',
    featured: true,
    category: 'Data Science',
  },
  {
    id: '8',
    title: 'Netflix UI Clone',
    slug: 'netflix-clone',
    description: 'Responsive Netflix landing page built with HTML & CSS.',
    tech: ['HTML', 'CSS', 'Responsive Design'],
    github_url: 'https://github.com/Harshad2321/Netflix-UI-Clone',
    demo_url: 'https://harshad2321.github.io/Netflix-UI-Clone/',
    image: '/netflix.png',
    featured: true,
    category: 'Web',
  },
];

export default projectsData;
